Needed to pass some environment variables to the gendocs.sh script.  Needed to set CXXFLAGS for them to take effect.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -36,8 +36,8 @@ script:
   - echo HOME=$HOME USER=$USER UID=$UID
   - docker pull ${IMAGE?}
   - /usr/bin/env ${COMPILER?} --version
-  - docker run --rm -it -v $PWD:/home/${USER?}/jaybeams ${IMAGE?} /bin/sh -c "cd /home/${USER?}/jaybeams && ./bootstrap && CXX=${COMPILER?} ./configure ${CONFIGUREFLAGS} && make -j 2 check"
-  - cat build/test-suite.log || echo "Could not print test logs"
+  - docker run --rm -it --env CXX=${COMPILER?} --env CXXFLAGS=${CXXFLAGS} -v $PWD:/home/${USER?}/jaybeams ${IMAGE?} /bin/sh -c "cd /home/${USER?}/jaybeams && ./bootstrap && ./configure ${CONFIGUREFLAGS} && make -j 2 check"
+  - cat test-suite.log || echo "Could not print test logs"
 
 install:
   - if [ "x${COVERAGE}" = "xyes" ]; then gem install coveralls-lcov ; fi
@@ -55,7 +55,7 @@ after_success:
   # ... create the Doxygen documentation inside the docker container,
   # and then push it using the host ...
   - if [ "x${GENDOCS}" == "xyes" ]; then
-    docker run --rm -it -v $PWD:/home/${USER?}/jaybeams ${IMAGE?} /bin/sh -c "cd /home/${USER?}/jaybeams && ci/gendocs.sh" ;
+    docker run --rm -it --env GIT_NAME=${GIT_NAME?} --env GIT_EMAIL=${GIT_EMAIL?} -v $PWD:/home/${USER?}/jaybeams ${IMAGE?} /bin/sh -c "cd /home/${USER?}/jaybeams && ci/gendocs.sh" ;
     git push https://${GH_TOKEN?}@github.com/coryan/jaybeams gh-pages ;
     fi
 
